[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
optimizer = true
optimizer_runs = 200
solc = "0.8.19"
rpc_endpoints = { mantle = "https://rpc.mantle.xyz" }

[profile.release]
via_ir = true
[rpc_endpoints]
mantlesepolia = "https://rpc.sepolia.mantle.xyz"

